### ISSUE TITLE
Set camera position from configuration file

### ISSUE THREAD

**Issue by rmm-fcul** [larics/assisi-playground#43]
- consistency for taking screenshots
- convenience for interactive simulation

**Comment by dmiklic** [comment]
@plsm could you please take a look at this?

**Comment by plsm** [comment]
I'll implement this.

**Comment by rmm-fcul** [comment]
Great.  It would be convenient (though not essential) if we could display the camera position values on-screen, so that one could find a desired viewing position through manual adjustment - and then be easy to reproduce. (Matlab's 3d plotting does this, for example).   Doing this either with a debug flag, or just display while the camera position is being adjusted, makes most sense to me.

**Comment by plsm** [comment]
In order to add this feature, I have to add a functionality to enki. The camera attributes are private. My proposal is to add methods to set camera properties. Concerning playground config file, my proposal is to add x,y and altitude parameters.

**Comment by rmm-fcul** [comment]
This PR extends #60 to allow custom setting of the yaw & pitch (which are far more fiddly to re-adjust consistently)
