### ISSUE TITLE
Make bee model parameter exploration easier

### ISSUE THREAD

**Issue by rmm-fcul** [larics/assisi-playground#55]
To aid exploration of bee behaviour, it would be useful to be able to parameterise the following aspects, without having to recompile the simulator:

a) body aspect ratio, body size (via length, width)
b) maximum speed the bees move at

If there are adverse side-effects for extreme sizes, please also document some basic reasoning or rules of thumb. (e.g. is it plausible to have a "point" bee that is 1mmx1mm, or would different sensors interfere with one another?)

**Comment by rmm-fcul** [comment]
The *maximum* range for bee object sensors is also a parameter in the initialiser, but I don't think this has any effect on the behaviours we are using for the bees, at least.  The behavioural code applies a threshold (distance) to pay attention to.  
If the efficiency of the overall simulation is influenced by the maximum range, it could make sense to have this as a config parameter as well.

**Comment by dmiklic** [comment]
Should be fixed by be9a2354ec95eab8ce4cf244ce73dcb3b48f32ec. Please sync with the master branch, give it a try and let me know if I can close this.

Regarding the maximum sensor range, I don't think it affects efficiency. Besides, that issue should be taken care of differently (i.e. touch sensor).

**Comment by dmiklic** [comment]
@rmm-fcul please let me know if the implemented solution fits the bill and whether we can close this.

**Comment by rmm-fcul** [comment]
The solution works fine.  I have only formally tested the maximum speed of agents, but visually I see bees getting bigger/wider/taller when I modify the other new .cfg file parameters.
