### ISSUE TITLE
Loading and saving heat state

### ISSUE THREAD

**Issue by plsm** [larics/assisi-playground#78]
I have corrected a bug when loading the heat state from a text file. Cells heat diffusivity wasn't initialized. Check branch heat-state

The first two lines of the text file contain parameters of the heat model. They should be ones present in the configuration file. Right now too much information is in these two lines.

**Comment by rmm-fcul** [comment]
this issue report is a bit confusing because it refers to a fix, not a problem.
I think it could be closed.
(the PR #79 includes a resolution)
(the issue #80 describes the related feature request)

**Comment by dmiklic** [comment]
Closing, as per Rob's comment.
